INSERT INTO players (name) VALUES ('Иван Иванович');
INSERT INTO players (name) VALUES ('Дмитрий Угоров');
INSERT INTO players (name) VALUES ('Евгений Поросюк');
INSERT INTO players (name) VALUES ('Слабый Игрок');
INSERT INTO players (name) VALUES ('Евгений Силач');
INSERT INTO players (name) VALUES ('Синее Ведро');
INSERT INTO players (name) VALUES ('Копатель Онлайн');
INSERT INTO players (name) VALUES ('Мужчина');
INSERT INTO players (name) VALUES ('Опасный Бандит');
INSERT INTO players (name) VALUES ('Мурило Бенисио');
INSERT INTO players (name) VALUES ('Джована Антонелли');
INSERT INTO players (name) VALUES ('Вера Фишер');
INSERT INTO players (name) VALUES ('Элли Тотошкина');

INSERT INTO matches (player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO matches (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (9, 10, 9);
INSERT INTO matches (player1, player2, winner) VALUES (1, 3, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 4, 2);
INSERT INTO matches (player1, player2, winner) VALUES (5, 7, 7);
INSERT INTO matches (player1, player2, winner) VALUES (6, 8, 6);
INSERT INTO matches (player1, player2, winner) VALUES (9, 1, 1);
INSERT INTO matches (player1, player2, winner) VALUES (10, 2, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 5, 3);
INSERT INTO matches (player1, player2, winner) VALUES (4, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (7, 9, 9);
INSERT INTO matches (player1, player2, winner) VALUES (8, 10, 8);
INSERT INTO matches (player1, player2, winner) VALUES (11, 1, 11);
INSERT INTO matches (player1, player2, winner) VALUES (3, 10, 3);
INSERT INTO matches (player1, player2, winner) VALUES (12, 11, 11);